#!/usr/bin/with-contenv bash

set -x

CONFIG_FILE="/etc/postsrsd.conf"
SECRET_FILE="/etc/postsrsd.secret"

: ${SRS_DOMAIN:=localhost.localnet}
# Generate by running 'dd if=/dev/random bs=18 count=1 | base64'
: ${SRS_SECRET:="setthistoaverylongstring"}
: ${SRS_EXCLUDE_DOMAINS:=""}
: ${SRS_SEPARATOR:="="}
: ${SRS_SOCKET_PORT:=10003}
: ${SRS_HASHLENGTH:=4}
: ${SRS_HASHMIN:=4}
: ${RUN_AS:=postsrsd}
: ${CHROOT:=/var/lib/postsrsdr}
: ${SRS_LISTEN_ADDRESS:="0.0.0.0"}

mkdir -p ${CHROOT}
chown -R ${RUN_AS} ${CHROOT}

echo "domains = {${SRS_EXCLUDE_DOMAINS}}" > "${CONFIG_FILE}"
echo "srs-domain = ${SRS_DOMAIN}" >> "${CONFIG_FILE}"
echo "socketmap = inet:${SRS_LISTEN_ADDRESS}:${SRS_SOCKET_PORT}" >> "${CONFIG_FILE}"
echo "keep-alive = 30" >> "${CONFIG_FILE}"
echo "original-envelope = embedded" >> "${CONFIG_FILE}"
echo "secrets-file = \"${SECRET_FILE}\"" >> "${CONFIG_FILE}"
echo "separator = \"${SRS_SEPARATOR}\"" >> "${CONFIG_FILE}"
echo "original-envelope = embedded" >> "${CONFIG_FILE}"
echo "hash-length = ${SRS_HASHLENGTH}" >> "${CONFIG_FILE}"
echo "hash-minimum = ${SRS_HASHMIN}" >> "${CONFIG_FILE}"
echo "always-rewrite = off" >> "${CONFIG_FILE}"
echo "unprivileged-user = ${RUN_AS}" >> "${CONFIG_FILE}"
echo "chroot-dir = ${CHROOT}" >> "${CONFIG_FILE}"
echo "syslog = on" >> "${CONFIG_FILE}"

echo "${SRS_SECRET}" > "${SECRET_FILE}"

/usr/sbin/postsrsd -C "${CONFIG_FILE}"
